### PR TITLE
fix: deduplicate lesson progress data

### LINKED ISSUE #1116: Total TypeScript: Can't un-complete lessons
I can't remove the "complete" status from a lesson once it has been marked complete. See attached video. The same is happening for other sections/lessons as well.

https://github.com/skillrecordings/products/assets/8353666/14a8a4c5-544e-4050-bbd1-ffdc5cb5f27b

It seems to work fine in the dev environment, which makes this a less than ideal bug report, but below is the tRPC mutation and following invalidated queries. Without having spent much time in the codebase, my first guess would be that it could be related to `sectionId` and `moduleId` being null?

Let me know if there's anything else I can provide to help track this down.

#### payload: 
`{0: {json: {lessonSlug: "generic-inference-through-multiple-type-helpers"}}}`
#### response:
```json
[
    {
        "result": {
            "data": {
                "json": {
                    "id": "6d786a53-d1b1-462c-aecd-98025ffe048e",
                    "userId": "18d602df-ba8b-4b24-be90-a3c95d4eac27",
                    "lessonId": "ZQ2yaFmbSrO44GD5qsZryf",
                    "sectionId": null,
                    "moduleId": null,
                    "lessonSlug": "generic-inference-through-multiple-type-helpers",
                    "lessonVersion": null,
                    "completedAt": "2023-08-15T10:07:09.364Z",
                    "updatedAt": "2023-08-15T10:07:09.364Z",
                    "createdAt": "2023-08-15T09:40:14.703Z"
                },
                "meta": {
                    "values": {
                        "completedAt": [
                            "Date"
                        ],
                        "updatedAt": [
                            "Date"
                        ],
                        "createdAt": [
                            "Date"
                        ]
                    }
                }
            }
        }
    }
]
```
#### payload
```json
{
   "0":{
      "json":{
         "slug":"advanced-react-with-typescript"
      }
   },
   "1":{
      "json":{
         "id":"nSYMozlU5vY3jWrxhWGSnG"
      }
   },
   "2":{
      "json":{
         "slug":"generic-inference-through-multiple-type-helpers",
         "type":"solution"
      }
   },
   "3":{
      "json":{
         "type":"solution",
         "slug":"generic-inference-through-multiple-type-helpers",
         "module":"advanced-react-with-typescript",
         "section":"using-generics-with-components"
      }
   },
   "4":{
      "json":{
         "moduleSlug":"advanced-react-with-typescript",
         "moduleType":"workshop",
         "lessonSlug":"generic-inference-through-multiple-type-helpers",
         "sectionSlug":"using-generics-with-components",
         "isSolution":true,
         "convertkitSubscriberId":null
      },
      "meta":{
         "values":{
            "convertkitSubscriberId":[
               "undefined"
            ]
         }
      }
   },
   "5":{
      "json":{
         "query":""
      }
   },
   "6":{
      "json":null,
      "meta":{
         "values":[
            "undefined"
         ]
      }
   }
}
```
#### response
```json
[
    {
        "result": {
            "data": {
                "json": {
                    "moduleId": "b66dff24-be12-458a-9cf7-e6050e0b9ba9",
                    "moduleCompleted": false,
                    "percentComplete": 68,
                    "lessonCount": 31,
                    "completedLessonCount": 21,
                    "nextLesson": {
                        "id": "21d1ce0c-f046-4306-8299-580811e0d677",
                        "slug": "conditionally-require-props-with-discriminated-unions"
                    },
                    "nextSection": {
                        "id": "2e03435c-85c7-4646-970c-024cad526513",
                        "slug": "advanced-props"
                    },
                    "sections": [
                        {
                            "id": "2e03435c-85c7-4646-970c-024cad526513",
                            "slug": "advanced-props",
                            "sectionCompleted": false,
                            "percentComplete": 92,
                            "lessonCount": 12,
                            "completedLessonCount": 11,
                            "lessons": [
                                {
                                    "id": "2507a86e-d6c5-4962-80cb-1f113a950519",
                                    "slug": "type-checking-react-props-with-discriminated-unions",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "9a32982c-040c-425e-8a6e-29c771be9ed1",
                                    "slug": "destructuring-discriminated-unions-in-react-props",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "7ade0c7b-f020-4995-905d-2cff77be47b0",
                                    "slug": "adding-a-prop-required-across-discriminated-union-variants",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "027ed466-86cb-47a1-99f0-23d5c879e198",
                                    "slug": "differentiating-props-with-a-boolean-discriminator",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "37acfd59-1f74-4302-8893-0b18b45660f2",
                                    "slug": "using-the-record-type-to-represent-an-empty-object",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "21d1ce0c-f046-4306-8299-580811e0d677",
                                    "slug": "conditionally-require-props-with-discriminated-unions",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "13939cd0-9b99-48c8-81d3-85881c15dbac",
                                    "slug": "finding-a-better-type-definition-for-a-mapped-component",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "a818d7fc-c6b9-4f3a-9b71-c485245778a1",
                                    "slug": "syncing-types-without-manual-updates",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "bc9daac6-21ce-4e2a-89ad-8aa52eee95c9",
                                    "slug": "the-partial-autocompletion-quirk",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "01a509ea-24df-40c4-a2f3-0ddce489653b",
                                    "slug": "extracting-keys-and-values-from-a-type",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "8647853a-b63c-48aa-8db0-6afedea22dac",
                                    "slug": "ensuring-correct-inference-for-prop-types",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "8e34be51-f1b6-4b94-8093-a2d150fb6214",
                                    "slug": "inference-from-a-single-source-of-truth",
                                    "lessonCompleted": true
                                }
                            ]
                        },
                        {
                            "id": "3631c5d3-3956-4b4e-93d0-149faa46375a",
                            "slug": "using-generics-with-components",
                            "sectionCompleted": false,
                            "percentComplete": 82,
                            "lessonCount": 11,
                            "completedLessonCount": 9,
                            "lessons": [
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsYluD",
                                    "slug": "dry-out-code-with-generic-type-helpers",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "5Ft6TKkt6aO0hMZBJfrKNN",
                                    "slug": "refactoring-to-a-type-helper",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsYqXy",
                                    "slug": "constraining-a-type-helper-to-accept-specific-values",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsZfMA",
                                    "slug": "adding-type-arguments-to-a-hook",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsZgew",
                                    "slug": "wrapping-a-generic-function-inside-of-another",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsZjGU",
                                    "slug": "applying-generics-to-components",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "5Ft6TKkt6aO0hMZBJfrdVm",
                                    "slug": "generics-in-class-components",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "Pp5cHWxuC2jFClUK8QUOKC",
                                    "slug": "passing-type-arguments-to-components",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsZryf",
                                    "slug": "generic-inference-through-multiple-type-helpers",
                                    "lessonCompleted": true
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsZtHR",
                                    "slug": "mutations-with-generic-hooks",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "ZQ2yaFmbSrO44GD5qsZvsz",
                                    "slug": "generics-arent-always-the-answer",
                                    "lessonCompleted": false
                                }
                            ]
                        },
                        {
                            "id": "abf547c5-582b-4b4d-a007-1aa76af4395c",
                            "slug": "advanced-hooks",
                            "sectionCompleted": false,
                            "percentComplete": 0,
                            "lessonCount": 8,
                            "completedLessonCount": 0,
                            "lessons": [
                                {
                                    "id": "76ewoxhAm9hNbPwR5adZyo",
                                    "slug": "fixing-type-inference-in-a-custom-react-hook",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "76ewoxhAm9hNbPwR5adeYA",
                                    "slug": "strongly-typing-react-context",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "mlQRzbyTLyVw7G9D8Y7f4S",
                                    "slug": "using-typescript-to-manage-complex-state",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "Ini7I8Tmq64qDWCLHGIvlS",
                                    "slug": "using-discriminated-unions-in-usestate",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "Ini7I8Tmq64qDWCLHGIxv0",
                                    "slug": "discriminated-tuples-in-custom-hooks",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "76ewoxhAm9hNbPwR5aenCM",
                                    "slug": "function-overloads-for-better-type-inference",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "Ini7I8Tmq64qDWCLHGJ1Ri",
                                    "slug": "mimicking-usestate-behavior-with-function-overloads",
                                    "lessonCompleted": false
                                },
                                {
                                    "id": "76ewoxhAm9hNbPwR5aew9G",
                                    "slug": "using-generics-when-currying-hooks",
                                    "lessonCompleted": false
                                }
                            ]
                        }
                    ],
                    "lessons": [
                        {
                            "id": "2507a86e-d6c5-4962-80cb-1f113a950519",
                            "slug": "type-checking-react-props-with-discriminated-unions",
                            "lessonCompleted": true
                        },
                        {
                            "id": "9a32982c-040c-425e-8a6e-29c771be9ed1",
                            "slug": "destructuring-discriminated-unions-in-react-props",
                            "lessonCompleted": true
                        },
                        {
                            "id": "7ade0c7b-f020-4995-905d-2cff77be47b0",
                            "slug": "adding-a-prop-required-across-discriminated-union-variants",
                            "lessonCompleted": true
                        },
                        {
                            "id": "027ed466-86cb-47a1-99f0-23d5c879e198",
                            "slug": "differentiating-props-with-a-boolean-discriminator",
                            "lessonCompleted": true
                        },
                        {
                            "id": "37acfd59-1f74-4302-8893-0b18b45660f2",
                            "slug": "using-the-record-type-to-represent-an-empty-object",
                            "lessonCompleted": true
                        },
                        {
                            "id": "21d1ce0c-f046-4306-8299-580811e0d677",
                            "slug": "conditionally-require-props-with-discriminated-unions",
                            "lessonCompleted": false
                        },
                        {
                            "id": "13939cd0-9b99-48c8-81d3-85881c15dbac",
                            "slug": "finding-a-better-type-definition-for-a-mapped-component",
                            "lessonCompleted": true
                        },
                        {
                            "id": "a818d7fc-c6b9-4f3a-9b71-c485245778a1",
                            "slug": "syncing-types-without-manual-updates",
                            "lessonCompleted": true
                        },
                        {
                            "id": "bc9daac6-21ce-4e2a-89ad-8aa52eee95c9",
                            "slug": "the-partial-autocompletion-quirk",
                            "lessonCompleted": true
                        },
                        {
                            "id": "01a509ea-24df-40c4-a2f3-0ddce489653b",
                            "slug": "extracting-keys-and-values-from-a-type",
                            "lessonCompleted": true
                        },
                        {
                            "id": "8647853a-b63c-48aa-8db0-6afedea22dac",
                            "slug": "ensuring-correct-inference-for-prop-types",
                            "lessonCompleted": true
                        },
                        {
                            "id": "8e34be51-f1b6-4b94-8093-a2d150fb6214",
                            "slug": "inference-from-a-single-source-of-truth",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsYluD",
                            "slug": "dry-out-code-with-generic-type-helpers",
                            "lessonCompleted": true
                        },
                        {
                            "id": "5Ft6TKkt6aO0hMZBJfrKNN",
                            "slug": "refactoring-to-a-type-helper",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsYqXy",
                            "slug": "constraining-a-type-helper-to-accept-specific-values",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsZfMA",
                            "slug": "adding-type-arguments-to-a-hook",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsZgew",
                            "slug": "wrapping-a-generic-function-inside-of-another",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsZjGU",
                            "slug": "applying-generics-to-components",
                            "lessonCompleted": true
                        },
                        {
                            "id": "5Ft6TKkt6aO0hMZBJfrdVm",
                            "slug": "generics-in-class-components",
                            "lessonCompleted": true
                        },
                        {
                            "id": "Pp5cHWxuC2jFClUK8QUOKC",
                            "slug": "passing-type-arguments-to-components",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsZryf",
                            "slug": "generic-inference-through-multiple-type-helpers",
                            "lessonCompleted": true
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsZtHR",
                            "slug": "mutations-with-generic-hooks",
                            "lessonCompleted": false
                        },
                        {
                            "id": "ZQ2yaFmbSrO44GD5qsZvsz",
                            "slug": "generics-arent-always-the-answer",
                            "lessonCompleted": false
                        },
                        {
                            "id": "76ewoxhAm9hNbPwR5adZyo",
                            "slug": "fixing-type-inference-in-a-custom-react-hook",
                            "lessonCompleted": false
                        },
                        {
                            "id": "76ewoxhAm9hNbPwR5adeYA",
                            "slug": "strongly-typing-react-context",
                            "lessonCompleted": false
                        },
                        {
                            "id": "mlQRzbyTLyVw7G9D8Y7f4S",
                            "slug": "using-typescript-to-manage-complex-state",
                            "lessonCompleted": false
                        },
                        {
                            "id": "Ini7I8Tmq64qDWCLHGIvlS",
                            "slug": "using-discriminated-unions-in-usestate",
                            "lessonCompleted": false
                        },
                        {
                            "id": "Ini7I8Tmq64qDWCLHGIxv0",
                            "slug": "discriminated-tuples-in-custom-hooks",
                            "lessonCompleted": false
                        },
                        {
                            "id": "76ewoxhAm9hNbPwR5aenCM",
                            "slug": "function-overloads-for-better-type-inference",
                            "lessonCompleted": false
                        },
                        {
                            "id": "Ini7I8Tmq64qDWCLHGJ1Ri",
                            "slug": "mimicking-usestate-behavior-with-function-overloads",
                            "lessonCompleted": false
                        },
                        {
                            "id": "76ewoxhAm9hNbPwR5aew9G",
                            "slug": "using-generics-when-currying-hooks",
                            "lessonCompleted": false
                        }
                    ]
                }
            }
        }
    },
    {
        "result": {
            "data": {
                "json": {
                    "_id": "nSYMozlU5vY3jWrxhWGSnG",
                    "muxPlaybackId": "PgBS5S01003Stf5mIv2MXMxpSMV3VeSOqqBctAk5wcbIw",
                    "transcript": "[00:00] Okie-dokie. So button group props. We can see probably that value is going to need to be a generic type, right? So let's call it T value for now. T value. And we need to instantiate this somewhere.\n\n[00:13] So let's put this on button group props. T value there. Now button group props is also going to need T value, as we can imagine. And this T value also needs to be put somewhere, needs to be instantiated from somewhere. So let's put it there.\n\n[00:27] Remove the end of the fragment, go T value, and then we're good to go. So this is working nicely. Now props.onclick here, we can see that argument type string is not assignable to parameter of type T value. T value could be instantiated with an arbitrary type, which could be unrelated to string.\n\n[00:46] Oh, okay. TypeScript. Thanks. Yeah, that's true. It could. It could. What it's saying there is it's saying that T value doesn't necessarily have to be related to string, right? So onclick currently receives T value, button value. It's a string, right? It's not T value.\n\n[01:05] So how do we get there then? Currently, you can see that value is being inferred as unknown here. That's because at this point, this onclick, it doesn't know what value is supposed to be.\n\n[01:19] So it doesn't try to do any inference there. So what we could do is we could just say, okay, add or delete here. And then this would work, you know, this is working fine. But actually, this is not very dry, because we've got add, delete here, and we've got add, delete here.\n\n[01:37] And actually, we don't even need to pass in add or delete here. It's not actually being constrained to the other one. So let's remove that. That's definitely not a solution. The way we've got to do this is we actually need to infer it from the type of value here.\n\n[01:51] So what we've got is an array of buttons in there. And we need to basically say, okay, this is T value, and this is T value. So let's make this a generic type. T value goes in there. And instead of value here, we've got T value there.\n\n[02:08] Now button, it's saying generic type button T value requires one type argument. So let's give it T value. And suddenly, it starts to work. Not quite. I thought it would work, actually, but it's not going to.\n\n[02:23] Now the reason that it's not working here is because actually, well, there's like an error up here, which sort of tells us why. T value is not assignable to type key or null or undefined.\n\n[02:34] We're using value in this little slot just here to basically type to pass a key, a unique key to the button to make sure that when it's rendered, it sort of doesn't re-render unnecessarily. You guys should know this.\n\n[02:48] When you're inside a map function inside of React, you should pass key to the elements that you're rendering in order to get it. So how do we know what type this expects? Well, if we command click into it, we can see that key, react.key is string or number, just that.\n\n[03:05] So what we want to do is, because T value can be anything, we actually want to constrain it to something that maps onto this key. So what we can do is T value extends, and let's just say extends string.\n\n[03:21] Oh, now we're getting somewhere. Now we're getting somewhere. So this value now, it's add or delete. So what's happening here is that basically we've got our button group, and let me actually just say const example equals button group,\n\n[03:37] and I'm going to call it manually. So by calling it manually, I'm just going to get a little bit better autocomplete here. So buttons, let's just say an empty array, and onClick like this, and I'll say our value here. And I'll actually do this below the button group so we don't get that error. There we go.\n\n[03:54] So now value here, we've got value string, so it's being inferred as, it's actually being inferred as string because we're not passing in any buttons. But as soon as we pass in a button, we've got our value, and let's just say wow, and label wow.\n\n[04:08] And we've got this value here is now being inferred as wow. So what's going on is that we instantiate our T value. That gets passed into button group props. That then passes itself down into button where it finally finds a place where it can infer from.\n\n[04:24] So this is the pattern that I wanted to show you. You're actually inferring your type argument through multiple different helpers. You've got this helper, and you've got this helper inside it. And even though it's down through a couple of different layers, it still manages to get the inference working.\n\n[04:40] And we used a constraint to make sure that it mapped onto the value of key here, or the type of key. Amazing."
                }
            }
        }
    },
    {
        "result": {
            "data": {
                "json": "src/05-generics/42-generic-inference-through-multiple-helpers.solution.tsx"
            }
        }
    },
    {
        "result": {
            "data": {
                "json": {
                    "_id": "ZQ2yaFmbSrO44GD5qsZtHR",
                    "_type": "exercise",
                    "_updatedAt": "2023-08-02T20:46:03Z",
                    "title": "Build a useMutation hook",
                    "slug": "mutations-with-generic-hooks",
                    "description": "Discover how to optimize your code by making use of generic hooks and type constraints in useMutation. "
                }
            }
        }
    },
    {
        "result": {
            "data": {
                "json": [
                    {
                        "action": "edit",
                        "subject": "User",
                        "conditions": {
                            "id": "18d602df-ba8b-4b24-be90-a3c95d4eac27"
                        }
                    },
                    {
                        "action": "view",
                        "subject": "Content"
                    },
                    {
                        "action": "view",
                        "subject": "Invoice"
                    },
                    {
                        "action": "view",
                        "subject": "Content"
                    }
                ]
            }
        }
    },
    {
        "result": {
            "data": {
                "json": [
                    {
                        "_type": "module",
                        "moduleType": "workshop",
                        "section": null,
                        "description": null,
                        "_score": 6.25902,
                        "module": null,
                        "title": "TypeScript Generics",
                        "_id": "235172fa-949e-48c3-91e8-43dc53230ee8",
                        "slug": {
                            "current": "typescript-generics",
                            "_type": "slug"
                        }
                    },
                    {
                        "moduleType": "workshop",
                        "description": null,
                        "_score": 6.25902,
                        "slug": {
                            "current": "advanced-typescript-patterns",
                            "_type": "slug"
                        },
                        "_type": "module",
                        "section": null,
                        "_id": "24001fa9-ba2b-4c85-9269-11cd6ff79252",
                        "title": "Advanced TypeScript Patterns",
                        "module": null
                    },
                    {
                        "_id": "58ae5ac7-125a-4c31-8011-c2c255f3de6b",
                        "description": "Free interactive video tutorial that will help you get started with TypeScript.",
                        "_type": "module",
                        "moduleType": "tutorial",
                        "section": null,
                        "module": null,
                        "_score": 6.25902,
                        "title": "Beginner's TypeScript",
                        "slug": {
                            "current": "beginners-typescript",
                            "_type": "slug"
                        }
                    },
                    {
                        "moduleType": "tutorial",
                        "section": null,
                        "module": null,
                        "_type": "module",
                        "description": "Get productive building applications with React and TypeScript with our interactive guide on React's types - from component props to useRef.",
                        "_score": 6.25902,
                        "_id": "80c4e5f4-278d-4c33-ae90-da334a9cc6f5",
                        "title": "React with TypeScript",
                        "slug": {
                            "current": "react-with-typescript",
                            "_type": "slug"
                        }
                    },
                    {
                        "_id": "b19979d5-3ffb-487a-bf3e-74b8155de9a3",
                        "slug": {
                            "current": "typescript-expert-interviews",
                            "_type": "slug"
                        },
                        "_score": 6.25902,
                        "module": null,
                        "title": "TypeScript Expert Interviews",
                        "_type": "module",
                        "moduleType": "bonus",
                        "section": null,
                        "description": null
                    },
                    {
                        "_score": 6.25902,
                        "moduleType": "workshop",
                        "description": "Expert-level knowledge for typing your React apps with TypeScript.",
                        "section": null,
                        "module": null,
                        "_id": "b66dff24-be12-458a-9cf7-e6050e0b9ba9",
                        "title": "Advanced React with TypeScript",
                        "slug": {
                            "_type": "slug",
                            "current": "advanced-react-with-typescript"
                        },
                        "_type": "module"
                    },
                    {
                        "_type": "module",
                        "section": null,
                        "slug": {
                            "current": "type-transformations",
                            "_type": "slug"
                        },
                        "_score": 6.25902,
                        "_id": "d6b51964-fd8f-41f1-b6ab-41ad64f2ccb0",
                        "title": "Type Transformations",
                        "moduleType": "workshop",
                        "module": null,
                        "description": null
                    },
                    {
                        "_score": 6.25902,
                        "_type": "module",
                        "moduleType": "tutorial",
                        "section": null,
                        "module": null,
                        "_id": "e607fabb-d959-4753-981f-0fa06392c5a6",
                        "title": "Zod",
                        "slug": {
                            "current": "zod",
                            "_type": "slug"
                        },
                        "description": "Zod is a TypeScript-first schema declaration and validation library. In this tutorial, Matt Pocock has prepared a set of exercises that will help you level up."
                    },
                    {
                        "section": {
                            "_id": "f4acc33d-0b4a-43d8-b9af-2d72ef4a759b",
                            "slug": "identity-functions",
                            "title": "Identity Functions"
                        },
                        "description": "Reverse mapped types allow changing inference in identity functions to infer from input, rather than output. Mind-bending, but cool!\n\n\n\n",
                        "_id": "017bae08-24a8-4ab8-bd5e-2537aede2489",
                        "title": "Reverse Mapped Types",
                        "slug": {
                            "current": "reverse-mapped-types",
                            "_type": "slug"
                        },
                        "_score": 1.5,
                        "_type": "exercise",
                        "moduleType": null,
                        "module": {
                            "_id": "24001fa9-ba2b-4c85-9269-11cd6ff79252",
                            "slug": {
                                "current": "advanced-typescript-patterns",
                                "_type": "slug"
                            },
                            "title": "Advanced TypeScript Patterns",
                            "moduleType": "workshop"
                        }
                    },
                    {
                        "section": {
                            "_id": "2e03435c-85c7-4646-970c-024cad526513",
                            "slug": "advanced-props",
                            "title": "Advanced Props"
                        },
                        "_score": 1.5,
                        "module": {
                            "_id": "b66dff24-be12-458a-9cf7-e6050e0b9ba9",
                            "slug": {
                                "current": "advanced-react-with-typescript",
                                "_type": "slug"
                            },
                            "title": "Advanced React with TypeScript",
                            "moduleType": "workshop"
                        },
                        "title": "Extracting Keys and Values from a Type",
                        "_type": "exercise",
                        "moduleType": null,
                        "description": "Using `as const` and indexed access types helps you extract keys and values from a type.",
                        "_id": "01a509ea-24df-40c4-a2f3-0ddce489653b",
                        "slug": {
                            "current": "extracting-keys-and-values-from-a-type",
                            "_type": "slug"
                        }
                    },
                    {
                        "title": "Differentiating Props With a Boolean Discriminator",
                        "slug": {
                            "current": "differentiating-props-with-a-boolean-discriminator",
                            "_type": "slug"
                        },
                        "_type": "exercise",
                        "moduleType": null,
                        "section": {
                            "_id": "2e03435c-85c7-4646-970c-024cad526513",
                            "slug": "advanced-props",
                            "title": "Advanced Props"
                        },
                        "module": {
                            "_id": "b66dff24-be12-458a-9cf7-e6050e0b9ba9",
                            "slug": {
                                "current": "advanced-react-with-typescript",
                                "_type": "slug"
                            },
                            "title": "Advanced React with TypeScript",
                            "moduleType": "workshop"
                        },
                        "_score": 1.5,
                        "_id": "027ed466-86cb-47a1-99f0-23d5c879e198",
                        "description": "Handle a situation where a Boolean is used as a discriminator in a discriminated union, and learn how to use a default value to avoid passing unnecessary props."
                    },
                    {
                        "section": {
                            "_id": "933c921b-b207-4415-a1f7-ee93330bcdb4",
                            "slug": "conditional-types-and-infer",
                            "title": "Conditional Types and Infer"
                        },
                        "description": "You may want to extract from a library function's return, but don't want to declare a type annotation for it. This is solved with infer and a conditional type.",
                        "_id": "02dae7f7-6f7b-42fe-b0fd-9ac88b64fc1d",
                        "_score": 1.5,
                        "title": "Extract the Result of an Async Function",
                        "slug": {
                            "current": "extract-the-result-of-an-async-function",
                            "_type": "slug"
                        },
                        "_type": "exercise",
                        "moduleType": null,
                        "module": {
                            "_id": "d6b51964-fd8f-41f1-b6ab-41ad64f2ccb0",
                            "slug": {
                                "current": "type-transformations",
                                "_type": "slug"
                            },
                            "title": "Type Transformations",
                            "moduleType": "workshop"
                        }
                    },
                    {
                        "_id": "0306e5b6-2991-4549-8a23-b28922a4ca65",
                        "module": {
                            "_id": "235172fa-949e-48c3-91e8-43dc53230ee8",
                            "slug": {
                                "current": "typescript-generics",
                                "_type": "slug"
                            },
                            "title": "TypeScript Generics",
                            "moduleType": "workshop"
                        },
                        "slug": {
                            "current": "passing-type-arguments-in-cal-com",
                            "_type": "slug"
                        },
                        "description": "The repo for cal.com contains several examples of how passing type arguments allows for overriding the weaknesses of external libraries.",
                        "section": {
                            "_id": "b086afd5-81e9-4a50-a9a6-a15b0c169240",
                            "slug": "passing-type-arguments",
                            "title": "Passing Type Arguments"
                        },
                        "_score": 1.5,
                        "title": "Passing Type Arguments in cal.com",
                        "_type": "explainer",
                        "moduleType": null
                    },
                    {
                        "moduleType": null,
                        "description": "The benefits of using template literal types for expressing string requirements over regexes, as explained by TypeScript's program manager.",
                        "module": {
                            "_id": "d6b51964-fd8f-41f1-b6ab-41ad64f2ccb0",
                            "slug": {
                                "current": "type-transformations",
                                "_type": "slug"
                            },
                            "title": "Type Transformations",
                            "moduleType": "workshop"
                        },
                        "_score": 1.5,
                        "_type": "explainer",
                        "slug": {
                            "current": "template-literal-types-vs-regexes",
                            "_type": "slug"
                        },
                        "section": {
                            "_id": "933c921b-b207-4415-a1f7-ee93330bcdb4",
                            "slug": "conditional-types-and-infer",
                            "title": "Conditional Types and Infer"
                        },
                        "_id": "07704e43-e1c4-4619-b175-85eb1b4e1036",
                        "title": "Template Literal Types Were Nearly Regexes"
                    },
                    {
                        "slug": {
                            "current": "specifying-where-inference-should-not-happen",
                            "_type": "slug"
                        },
                        "_type": "exercise",
                        "description": "Sometimes TypeScript infers when we don't want it to. The `F.NoInfer` utility from ts-toolbelt helps us avoid this problem.",
                        "module": {
                            "_id": "24001fa9-ba2b-4c85-9269-11cd6ff79252",
                            "slug": {
                                "current": "advanced-typescript-patterns",
                                "_type": "slug"
                            },
                            "title": "Advanced TypeScript Patterns",
                            "moduleType": "workshop"
                        },
                        "_id": "0786a1dc-3206-4cfa-8bfd-54c71cdf45d9",
                        "title": "Specifying Where Inference Should Not Happen",
                        "moduleType": null,
                        "section": {
                            "_id": "f4acc33d-0b4a-43d8-b9af-2d72ef4a759b",
                            "slug": "identity-functions",
                            "title": "Identity Functions"
                        },
                        "_score": 1.5
                    },
                    {
                        "_score": 1.5,
                        "slug": {
                            "current": "create-unions-out-of-array-values",
                            "_type": "slug"
                        },
                        "_type": "exercise",
                        "moduleType": null,
                        "module": {
                            "_id": "d6b51964-fd8f-41f1-b6ab-41ad64f2ccb0",
                            "slug": {
                                "current": "type-transformations",
                                "_type": "slug"
                            },
                            "title": "Type Transformations",
                            "moduleType": "workshop"
                        },
                        "description": "We can also create unions out of arrays. \n\nThere are ways in TypeScript to make a union from the entire array, or just some specified elements.",
                        "_id": "08624556-a36f-46d8-8c8f-657a8c8b99c9",
                        "title": "Create Unions out of Array Values",
                        "section": {
                            "_id": "d924280d-f776-4512-95fe-0d594f462dcd",
                            "slug": "unions-and-indexing",
                            "title": "Unions and Indexing"
                        }
                    },
                    {
                        "slug": {
                            "_type": "slug",
                            "current": "adding-react-to-a-typescript-project"
                        },
                        "moduleType": null,
                        "description": "There are a few steps to follow in order to add React to a TypeScript project.",
                        "_score": 1.5,
                        "_id": "08c86517-8589-42bf-b495-d6ebebad6012",
                        "title": "Adding React to a TypeScript Project",
                        "_type": "explainer",
                        "section": {
                            "_id": "a22e3908-d22b-4319-846c-b35e0b92971e",
                            "slug": "introduction",
                            "title": "Introduction"
                        },
                        "module": {
                            "_id": "80c4e5f4-278d-4c33-ae90-da334a9cc6f5",
                            "slug": {
                                "current": "react-with-typescript",
                                "_type": "slug"
                            },
                            "title": "React with TypeScript",
                            "moduleType": "tutorial"
                        }
                    },
                    {
                        "_id": "08e178b7-5131-450e-8876-b50b428c3a2e",
                        "_score": 1.5,
                        "module": {
                            "_id": "d6b51964-fd8f-41f1-b6ab-41ad64f2ccb0",
                            "slug": {
                                "current": "type-transformations",
                                "_type": "slug"
                            },
                            "title": "Type Transformations",
                            "moduleType": "workshop"
                        },
                        "title": "Get the Return Type of a Function",
                        "slug": {
                            "_type": "slug",
                            "current": "get-the-return-type-of-a-function"
                        },
                        "_type": "exercise",
                        "moduleType": null,
                        "section": {
                            "_id": "4c748816-5607-4678-9270-372bcbbf6398",
                            "slug": "inference-basics",
                            "title": "Inference Basics"
                        },
                        "description": null
                    },
                    {
                        "_score": 1.5,
                        "title": "Be Specific with Allowed Types",
                        "slug": {
                            "current": "union",
                            "_type": "slug"
                        },
                        "_id": "090f3fde-1563-4d88-a862-d99ba6a11462",
                        "_type": "exercise",
                        "moduleType": null,
                        "section": {
                            "_id": "bd153a21-5d5d-4fe7-a638-c9a87c316ae2",
                            "slug": "zod-section",
                            "title": "Zod Section"
                        },
                        "description": null,
                        "module": {
                            "_id": "e607fabb-d959-4753-981f-0fa06392c5a6",
                            "slug": {
                                "_type": "slug",
                                "current": "zod"
                            },
                            "title": "Zod",
                            "moduleType": "tutorial"
                        }
                    },
                    {
                        "moduleType": null,
                        "section": {
                            "_id": "2feb5937-0edd-4e0a-a415-e54cb8aa0237",
                            "slug": "template-literals",
                            "title": "Template Literals"
                        },
                        "description": "Examine real-world use cases for template literals by going through Mattermost’s source code.",
                        "_id": "094d520a-897a-4e41-bd76-2e033e5069ad",
                        "slug": {
                            "current": "template-literals-in-mattermost",
                            "_type": "slug"
                        },
                        "module": {
                            "_id": "d6b51964-fd8f-41f1-b6ab-41ad64f2ccb0",
                            "slug": {
                                "current": "type-transformations",
                                "_type": "slug"
                            },
                            "title": "Type Transformations",
                            "moduleType": "workshop"
                        },
                        "_type": "explainer",
                        "_score": 1.5,
                        "title": "Template Literals in Mattermost"
                    },
                    {
                        "moduleType": null,
                        "section": {
                            "_id": "bd153a21-5d5d-4fe7-a638-c9a87c316ae2",
                            "slug": "zod-section",
                            "title": "Zod Section"
                        },
                        "_score": 1.5,
                        "_id": "0b3d644c-03ca-42d4-9051-88ad75a2b8f6",
                        "slug": {
                            "current": "infer",
                            "_type": "slug"
                        },
                        "_type": "exercise",
                        "description": null,
                        "title": "Extract a Type from a Parser Object",
                        "module": {
                            "_id": "e607fabb-d959-4753-981f-0fa06392c5a6",
                            "slug": {
                                "_type": "slug",
                                "current": "zod"
                            },
                            "title": "Zod",
                            "moduleType": "tutorial"
                        }
                    }
                ]
            }
        }
    },
    {
        "result": {
            "data": {
                "json": [
                    {
                        "action": "edit",
                        "subject": "User",
                        "conditions": {
                            "id": "18d602df-ba8b-4b24-be90-a3c95d4eac27"
                        }
                    },
                    {
                        "action": "view",
                        "subject": "Invoice"
                    }
                ]
            }
        }
    }
]
```

### PR DESCRIPTION
**Pull request by vojtaholik**
fixes #1116 

Linear issue: https://linear.app/skillrecordings/issue/TT-342/app-should-gracefully-handle-duplicate-lessonprogress-records

gif

### CODE REVIEW

File: packages/skill-lesson/trpc/routers/module-progress.ts [hunk 1]
```diff
@@ -38,12 +39,20 @@ export const moduleProgressRouter = router({
         },
       })
 
+      const sortedModuleLessonProgress =
+        sortByLessonSlugNotNull(moduleLessonProgress)
+
+      const filteredModuleLessonProgress = uniqBy(
+        sortedModuleLessonProgress,
+        'lessonId',
+      )
```
Comment (jbranchaud) [inline packages/skill-lesson/trpc/routers/module-progress.ts:48]: Why do you sort by `lessonSlug` before filtering out records by unique `lessonId`?

I'm both curious and think it would be worth including a comment.

Comment (vojtaholik) [reply packages/skill-lesson/trpc/routers/module-progress.ts]: you're correct that is not required. I updated it so that it just sorts by `updatedAt` which will be enough to shift the most recent duplicate to the top resulting in `uniq` filtering out the second one.
